---
title: "this"
date: 2018-08-29
---

title: Pierce'spage
author: freaking me 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 words are here

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
